### ISSUE TITLE
Broken with CocoaPods : 1.0.1

### ISSUE THREAD

**Issue by ingmar80** [dustywusty/cocoapods-repo-svn#16]
Since the CocoaPods update 0.39 to 1.0 the cocoapods-repo-svn plugin seems to be broken:
### Command

```
/usr/local/bin/pod install
```
### Report
- What did you do?
- What did you expect to happen?
- What happened instead?
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d7ba89614855d257eaed5ce3f8bdaef7b029b082
               pods -  @ fatal: Not a git repository (or any of the parent directories): .git
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-repo-svn    : 2.0.1
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
### Podfile

``` ruby
platform :ios, '8.4'
use_frameworks!
plugin 'cocoapods-repo-svn', :sources => ['http://svn.XXXXXX.de/ios/pods']
source 'https://github.com/CocoaPods/Specs.git'

def pods
    pod 'Eureka', '~> 1.0'
#   pod 'BXConnect'
    pod 'MBProgressHUD', '~> 0.9'
end

target 'Spesen' do
    pods
end

target 'Spesen Dev' do
    pods
end

target 'Spesen Test' do
    pods
end

target 'Spesen Training' do
    pods
end
```
### Error

```
NoMethodError - undefined method `check_version_information' for #<Pod::Source::Manager:0x007fa1db2c04f0>
/Library/Ruby/Gems/2.0.0/gems/cocoapods-repo-svn-2.0.1/lib/pod/command/repo_svn.rb:117:in `block (2 levels) in update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-repo-svn-2.0.1/lib/pod/command/repo_svn.rb:104:in `block in update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-repo-svn-2.0.1/lib/pod/command/repo_svn.rb:103:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-repo-svn-2.0.1/lib/pod/command/repo_svn.rb:103:in `update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-repo-svn-2.0.1/lib/pod/command/repo_svn.rb:74:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-repo-svn-2.0.1/lib/cocoapods_plugin.rb:32:in `update_or_add_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-repo-svn-2.0.1/lib/cocoapods_plugin.rb:10:in `block (2 levels) in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-repo-svn-2.0.1/lib/cocoapods_plugin.rb:8:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-repo-svn-2.0.1/lib/cocoapods_plugin.rb:8:in `block in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/hooks_manager.rb:109:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/hooks_manager.rb:109:in `block (3 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/hooks_manager.rb:103:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/hooks_manager.rb:101:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/hooks_manager.rb:101:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/hooks_manager.rb:100:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:482:in `run_source_provider_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:143:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by rush397** [comment]
first remove cocoapods-repo-svn if you installed it before

- sudo gem uninstall cocoapods-repo-svn

welkiner's pull request did't merged to master, so try to install it with full url:

1. sudo gem install specific_install 
2. sudo gem specific_install https://github.com/welkiner/cocoapods-repo-svn

**Comment by ingmar80** [comment]
Thank You rush397, this works like a charm!
