### ISSUE TITLE
TypeError - no implicit conversion of Pod::Version into String

### ISSUE THREAD

**Issue by huangzhijia** [dustywusty/cocoapods-repo-svn#19]
### my Pods env
fatal: Not a git repository (or any of the parent directories): .git

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.6.13
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8378edd09f7072799ec75d6fc897a00e8cad3f14
               O2Specs - https://github.com/huangzhijia/O2Specs.git @ 045223113faa18dd2ec08a2afdf60ac55d7423e7
               PodSpecs -  @ fatal: Not a git repository (or any of the parent directories): .git
               PosSpecs - http://git.code.oa.com/ddspods/PosSpecs.git @ aec964e1c79ed39dc093d234df1b5c46f87aad97
               SVNPodSpecs -  @ fatal: Not a git repository (or any of the parent directories): .git
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-repo-svn    : 2.1.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
plugin 'cocoapods-repo-svn', :sources => [
        'http://mysvn.../trunk/IOSComponents/Pods/SVNPodSpecs/'
    ] 

platform :ios, "7.0" 
 
target 'TestPodsProj' do
  
   pod 'TestSvnRepo','1.0.0'

end
````

### Error

```
TypeError - no implicit conversion of Pod::Version into String
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.1.2/lib/cocoapods-downloader/subversion.rb:55:in `reference_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.1.2/lib/cocoapods-downloader/subversion.rb:26:in `download!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.1.2/lib/cocoapods-downloader/base.rb:82:in `block in download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader.rb:157:in `block in ui_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader.rb:156:in `ui_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.1.2/lib/cocoapods-downloader/base.rb:80:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader.rb:108:in `download_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader.rb:75:in `download_request'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader/cache.rb:171:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader/cache.rb:154:in `block in uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader/cache.rb:181:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader.rb:42:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/pod_source_installer.rb:120:in `download_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:355:in `install_source_of_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:322:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:321:in `block in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:313:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:313:in `install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:159:in `block in download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:157:in `download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:111:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by huangzhijia** [comment]
s.source       = { :svn => "svn://192.168.6.5:9600/wzhouhui/app/ios/ProjectManagerTest/QHLUtil", :tag => "#{s.version}" }

**Comment by huangzhijia** [comment]
my  xx.podspec is wrong，modify ".source" , Then pod Install is OK
s.source = { :svn => "svn://192.168.6.5:9600/wzhouhui/app/ios/ProjectManagerTest/QHLUtil", :tag => "#{s.version}" }
